# Generated by Django 4.1.1 on 2022-09-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("existing_database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Aggregated User Stat Data Latest Date"),
                            (1, "Aggregated User Group Stat Data Latest Date"),
                        ],
                        unique=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=225, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AggregatedUserStatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_date", models.DateField()),
                ("total_time", models.IntegerField()),
                ("task_count", models.FloatField()),
                ("swipes", models.FloatField()),
                ("area_swiped", models.FloatField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="existing_database.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="existing_database.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user", "timestamp_date")},
            },
        ),
        migrations.CreateModel(
            name="AggregatedUserGroupStatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_date", models.DateField()),
                ("total_time", models.IntegerField()),
                ("task_count", models.FloatField()),
                ("swipes", models.FloatField()),
                ("area_swiped", models.FloatField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="existing_database.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="existing_database.user",
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="existing_database.usergroup",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("project", "user", "user_group", "timestamp_date")
                },
            },
        ),
    ]
