# Generated by Django 4.1.1 on 2022-09-16 05:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('existing_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Aggregated User Stat Data Latest Date'), (1, 'Aggregated User Group Stat Data Latest Date')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AggregatedUserStatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_date', models.DateField()),
                ('total_time', models.DurationField()),
                ('task_count', models.FloatField()),
                ('swipes', models.FloatField()),
                ('area_swiped', models.FloatField()),
                ('user_group_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='existing_database.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='existing_database.user')),
            ],
            options={
                'unique_together': {('project', 'user', 'timestamp_date')},
            },
        ),
        migrations.CreateModel(
            name='AggregatedUserGroupStatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_date', models.DateField()),
                ('total_time', models.DurationField()),
                ('task_count', models.FloatField()),
                ('swipes', models.FloatField()),
                ('area_swiped', models.FloatField()),
                ('total_user_groups', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='existing_database.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='existing_database.user')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='existing_database.usergroup')),
            ],
            options={
                'unique_together': {('project', 'user', 'user_group', 'timestamp_date')},
            },
        ),
    ]
