# Generated by Django 4.1.1 on 2022-09-28 14:43

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregated", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="aggregatedtracking",
            managers=[
                ("cte_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="aggregatedusergroupstatdata",
            managers=[
                ("cte_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="aggregateduserstatdata",
            managers=[
                ("cte_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="aggregateduserstatdata",
            name="swipes",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="aggregateduserstatdata",
            name="task_count",
            field=models.IntegerField(),
        ),
    ]
