# Generated by Django 4.1.1 on 2022-12-02 10:49

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("existing_database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingSession",
            fields=[
                ("mapping_session_id", models.BigAutoField(primary_key=True)),
                ("project_id", models.CharField(max_length=999)),
                ("group_id", models.CharField(max_length=999)),
                ("user_id", models.CharField(max_length=999)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("items_count", models.SmallIntegerField(default=0)),
            ],
            options={
                "db_table": "mapping_sessions",
                "managed": settings.TESTING,
            },
            managers=[
                ("cte_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MappingSessionResult",
            fields=[
                ("mapping_session_id", models.BigIntegerField()),
                ("task_id", models.CharField(max_length=999)),
                ("result", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "mapping_sessions_results",
                "managed": settings.TESTING,
            },
            managers=[
                ("cte_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MappingSessionUserGroup",
            fields=[
                ("mapping_session_id", models.BigIntegerField()),
                ("user_group_id", models.CharField(max_length=999)),
            ],
            options={
                "db_table": "mapping_sessions_user_groups",
                "managed": settings.TESTING,
            },
            managers=[
                ("cte_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
